# https://numtide.github.io/devshell
[[commands]]
package = "just"

[[commands]]
name = "just lint"
help = "run ansible lint on playbook"
category = "just"
package = "just"

[[commands]]
name = "just galaxy"
help = "install dependencies from ansible-galaxy"
category = "just"
package = "just"

[[commands]]
name = "just setup"
help = "runs ansible.setup ad-hoc"
category = "just"
package = "just"

[[commands]]
name = "ansible"
category = "ansible"
package = "ansible"

[[commands]]
name = "ansible-galaxy"
help = "Ansible role and collection management"
category = "ansible"
package = "ansible"

[[commands]]
name = "ansible-vault"
help = "Ansible data encryption/decryption"
category = "ansible"
package = "ansible"

[[commands]]
category = "ansible"
package = "ansible-lint"

[devshell]
packages = [ "nodePackages_latest.nodejs" ] # needed for ansible-language-server
