---
- name: Setup
  hosts: all
  become: true
  tasks:
    - name: Install openssh
      ansible.builtin.apt:
        name:
          - openssh-client
          - openssh-server
        update_cache: true

    - name: Create semaphore user
      ansible.builtin.user:
        name: semaphore
        system: true
        password: $y$j9T$ue0y6ru3Sgu0UfWoO0l/W1$gBbkiB7Ef58fnE25VMvmzoPu5JIZ1QTO0X2CixGY/.6
        update_password: always
        groups: sudo
