- name: Setup
  hosts: all
  become: true
  handlers:
    - name: Restart sshd
      ansible.builtin.service:
        name: ssh
        state: restarted
  tasks:
    - name: Install openssh
      ansible.builtin.apt:
        name:
          - openssh-client
          - openssh-server
        update_cache: true

    - name: Enforce public key authentication for sshd
      ansible.builtin.copy:
        dest: /etc/ssh/sshd_config.d/enforce_pubkey_auth
        content: |
          PasswordAuthentication no
        owner: root
        group: root
        mode: '0644'
      notify:
        - Restart sshd

    - name: Disable root login via ssh
      ansible.builtin.copy:
        dest: /etc/ssh/sshd_config.d/disable_root_login
        content: |
          PremitRootLogin no
        owner: root
        group: root
        mode: '0644'
      notify:
        - Restart sshd

    - name: Create semaphore user
      ansible.builtin.user:
        name: semaphore
        system: true
        password: $y$j9T$ue0y6ru3Sgu0UfWoO0l/W1$gBbkiB7Ef58fnE25VMvmzoPu5JIZ1QTO0X2CixGY/.6
        update_password: always
        groups: sudo

    - name: Add authorized_keys for semaphore user
      ansible.posix.authorized_key:
        user: semaphore
        exclusive: true
        key: ssh-ed25519 AAAAC3NzaC1lZDI1NTE5AAAAIJ+dLFzhRSt6OWieyIWXOAEbPKEPmOWlqwALhO9sPr15
