- name: Install and configure tailscale
  hosts: tailscale
  become: true
  handlers:
    - name: Restart sshd
      ansible.builtin.service:
        name: ssh
        state: restarted

  tasks:
    - name: Fetch tailscale-archive-keyring
      ansible.builtin.get_url:
        url: https://pkgs.tailscale.com/stable/{{ ansible_distribution | lower }}/{{ ansible_distribution_release }}.noarmor.gpg
        dest: /etc/apt/keyrings/tailscale-archive-keyring.gpg
        owner: root
        group: root
        mode: '0755'

    - name: Configure tailscale archive
      ansible.builtin.copy:
        dest: /etc/apt/sources.list.d/tailscale.sources
        content: |
          X-Repolib-Name: tailscale
          Types: deb
          URIs: http://pkgs.tailscale.com/stable/{{ ansible_distribution | lower }}
          Suites: {{ ansible_distribution_release }}
          Components: main
          Signed-by: /etc/apt/keyrings/tailscale-archive-keyring.gpg
        owner: root
        group: root
        mode: '0755'

    - name: Install tailscale
      ansible.builtin.apt:
        name: tailscale
        update_cache: true

    - name: Create ssh override dir
      ansible.builtin.file:
        path: /etc/systemd/system/ssh.service.d
        state: directory
        owner: root
        group: root
        mode: '0755'

    - name: Override ssh to run after tailscale
      ansible.builtin.copy:
        dest: /etc/systemd/system/ssh.service.d/after_override.conf
        content: |
          [Unit]
          After=network.target auditd.service tailscaled.service
        owner: root
        group: root
        mode: '0644'
      notify: Restart sshd

    - name: Configure ssh to listen only on tailscale ips
      ansible.builtin.lineinfile:
        dest: /etc/ssh/sshd_config.d/tailscale.conf
        line: ListenAddress {{ item }}
      loop: "{{ tailscale_ips }}"
      when: tailscale_exclusive_ssh
      notify: Restart sshd
