- name: Install and configure tailscale
  hosts: tailscale
  become: true
  handlers:
    - name: Restart sshd
      ansible.builtin.service:
        name: ssh
        state: restarted

  tasks:
    - name: Configure tailscale archive
      ansible.builtin.deb822_repository:
        name: tailscale
        types: deb
        uris: http://pkgs.tailscale.com/stable/{{ ansible_distribution | lower }}
        suites: "{{ ansible_distribution_release }}"
        components: main
        signed_by: https://pkgs.tailscale.com/stable/{{ ansible_distribution | lower }}/{{ ansible_distribution_release }}.noarmor.gpg

    - name: Install tailscale
      ansible.builtin.apt:
        name: tailscale
        update_cache: true

    - name: Create ssh override dir
      ansible.builtin.file:
        path: /etc/systemd/system/ssh.service.d
        state: directory
        owner: root
        group: root
        mode: '0755'

    - name: Override ssh to run after tailscale
      ansible.builtin.copy:
        dest: /etc/systemd/system/ssh.service.d/after_override.conf
        content: |
          [Unit]
          After=network.target auditd.service tailscaled.service
        owner: root
        group: root
        mode: '0644'
      notify: Restart sshd

    - name: Configure ssh to listen only on tailscale ips
      ansible.buitlin.copy:
        dest: /etc/ssh/sshd_config.d/tailscale.conf
        content: |
          ListenAddress {{ item }}
      loop: "{{ tailscale_ips }}"
      when: tailscale_exclusive_ssh
      notify: Restart sshd
